package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/therelicai/therelic/internal/proxy"
	"github.com/therelicai/therelic/internal/trace"
	"github.com/oklog/ulid/v2"
	"github.com/spf13/cobra"
)

// newProxyStdioCmd returns the `relic proxy-stdio` command.
//
// proxy-stdio is an internal command used by `relic run --from-openclaw` to wrap
// individual MCP server processes with The Relic's policy engine.
//
// Usage:
//
//	relic proxy-stdio [--run-id <id>] [--trace-dir <dir>] [--policy <path>]
//	               [--mode <mode>] -- <command> [args...]
//
// When OpenClaw (or any agent framework) spawns an MCP server via stdio,
// the modified openclaw.json generated by `relic run --from-openclaw` replaces
// each stdio server entry with this command.  proxy-stdio:
//
//  1. Starts the real MCP server as a subprocess.
//  2. Mediates stdin/stdout between the caller (agent) and the MCP server.
//  3. Enforces policy and records every intercepted action in the trace.
//
// Environment variable fallbacks (used when flags are not supplied):
//
//	RELIC_RUN_ID     — run ID to use (overridden by --run-id)
//	RELIC_TRACE_DIR  — trace directory (overridden by --trace-dir)
//	RELIC_POLICY     — policy file path (overridden by --policy)
func newProxyStdioCmd() *cobra.Command {
	var (
		flagRunID    string
		flagTraceDir string
		flagPolicy   string
		flagMode     string
	)

	cmd := &cobra.Command{
		Use:          "proxy-stdio [flags] -- <command> [args...]",
		Short:        "Wrap an MCP stdio server with The Relic policy enforcement",
		Long:         `Internal command used by relic run --from-openclaw to proxy individual MCP servers.`,
		Args:         cobra.ArbitraryArgs,
		SilenceUsage: true,
		Hidden:       true, // internal — hide from top-level help
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return fmt.Errorf("proxy-stdio: no command specified")
			}

			// Resolve run ID: flag → env → fresh ID.
			runID := flagRunID
			if runID == "" {
				runID = os.Getenv("RELIC_RUN_ID")
			}
			standalone := runID == "" // true when not launched by relic run
			if standalone {
				runID = ulid.Make().String()
			}

			// Resolve trace directory: flag → env → default.
			traceDir := flagTraceDir
			if traceDir == "" {
				traceDir = os.Getenv("RELIC_TRACE_DIR")
			}
			if traceDir == "" {
				traceDir = filepath.Join(".tr", "traces")
			}

			// Resolve policy path: flag → env.
			policyPath := flagPolicy
			if policyPath == "" {
				policyPath = os.Getenv("RELIC_POLICY")
			}

			relicDir := filepath.Dir(traceDir)
			errW := cmd.ErrOrStderr()

			eng, red := loadEngineAndRedactor(errW, relicDir, policyPath, flagMode)

			// Open (or create) the trace file — appends to an existing run.
			tw, err := trace.NewTraceWriter(traceDir, runID)
			if err != nil {
				return fmt.Errorf("proxy-stdio: trace writer: %w", err)
			}
			defer tw.Close() //nolint:errcheck

			if standalone {
				if err := tw.WriteRunStart(runID, args[0], "", "", ""); err != nil {
					return fmt.Errorf("proxy-stdio: write run start: %w", err)
				}
			}

			onAction := func(ev trace.ActionEvent) {
				if err := tw.WriteAction(ev); err != nil {
					fmt.Fprintf(errW, "proxy-stdio: warning: write trace: %v\n", err)
				}
			}

			p := proxy.NewMCPProxy(runID, args[0], args[1:], eng, red, onAction)
			if err := p.Start(); err != nil {
				return fmt.Errorf("proxy-stdio: start mcp server: %w", err)
			}
			defer p.Close()

			// Serve until the caller closes its side (stdin → EOF) or the MCP
			// server exits.  Reads from os.Stdin (agent → proxy), writes to
			// os.Stdout (proxy → agent).
			if err := p.ServeStdio(nil, os.Stdin, os.Stdout); err != nil && err != io.EOF {
				return fmt.Errorf("proxy-stdio: serve: %w", err)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&flagRunID, "run-id", "", "Run ID to append trace events to (default: RELIC_RUN_ID env or new ID)")
	cmd.Flags().StringVar(&flagTraceDir, "trace-dir", "", "Trace directory (default: RELIC_TRACE_DIR env or .tr/traces)")
	cmd.Flags().StringVar(&flagPolicy, "policy", "", "Policy file path (default: RELIC_POLICY env or .tr/policy.yaml)")
	cmd.Flags().StringVar(&flagMode, "mode", "", "Override policy mode: enforce | audit | permissive")

	return cmd
}
